---
- name: Setup Application Folder and Git Repository
  hosts: webservers
  become: true
  vars:
    # Update these values with your actual details
    repo_url: "https://github.com/Sanilkhande06/Tutedude.git"
    app_dir: "/home/ubuntu/student_app"
    backend_app_dir: "/home/ubuntu/student_app/DevOps/Jenkins_CICD_Sani_Rajesh_Lokhande/backend"
    frontend_app_dir: "/home/ubuntu/student_app/DevOps/Jenkins_CICD_Sani_Rajesh_Lokhande/frontend"

  tasks:

    # 1. INSTALL SYSTEM PACKAGES
    - name: Update apt cache and install Core System Packages
      ansible.builtin.apt:
        name:
          - git
          - python3
          - python3-pip
          - python3-venv
          - nodejs
          - npm
        state: present
        update_cache: true

    # 2. CREATE APPLICATION DIRECTORY
    - name: Ensure the application directory exists
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    # 3. PULL GIT REPOSITORY
    - name: Clone the Git repository into the application folder
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: main # Change to your default branch name (e.g., master)
        force: yes

    # 4. SETUP PYTHON VENV AND FLASK INSIDE THE APP FOLDER
    - name: Create Python venv and install dependencies inside application folder
      ansible.builtin.pip:
        name:
          - flask
          - python-dotenv
        virtualenv: "{{ backend_app_dir }}/venv"
        virtualenv_command: python3 -m venv
        state: present

    # 5. CONFIGURE SYSTEMD SERVICE FOR FLASK USING YOUR CLONED FILE
    - name: Copy systemd service file from the backend repository to system systemd folder
      ansible.builtin.copy:
        src: "{{ backend_app_dir }}/student_flask_app_terraform.service" # Location inside your cloned repo
        dest: /etc/systemd/system/student_flask_app_terraform.service     # System location
        remote_src: yes                               # Tells Ansible the source file is already on the remote host
        mode: '0644'

    - name: Reload systemd daemon to recognize the new service
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Ensure Flask service is started and enabled on boot
      ansible.builtin.systemd:
        name: flaskapp
        state: started
        enabled: yes
